#!/usr/bin/env python3
"""Generate session_config.js for the experiment HTML pages.

Reads /etc/genius/session.env (or explicit CLI args) and writes
EXPERIMENT_DOCUMENTS/organiser/session_config.js so that participant HTML
pages can auto-fill participant ID, session ID, condition, desktop URL,
username, and password — without the participant typing anything.

Usage:
  # Normal: read from /etc/genius/session.env (runs on the VM at boot)
  python SCRIPTS/generate_session_config.py

  # Override: useful for local testing
  python SCRIPTS/generate_session_config.py \
      --participant-id manual-01 --session-id S1 --condition manual \
      --desktop-url https://1.2.3.4:8443/#genius --password secret123
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


ENV_FILE = Path("/etc/genius/session.env")
DEFAULT_OUTPUT = Path("EXPERIMENT_DOCUMENTS/organiser/session_config.js")


def parse_env_file(path: Path) -> dict:
    result = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        line = re.sub(r"^export\s+", "", line)
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        value = value.strip().strip('"').strip("'")
        result[key.strip()] = value
    return result


def build_config(participant_id, session_id, condition, desktop_url, username, password):
    return {
        "participantId": participant_id,
        "sessionId": session_id,
        "condition": condition,
        "desktopUrl": desktop_url,
        "username": username,
        "password": password,
        "generatedAt": datetime.now(timezone.utc).isoformat(),
    }


def write_js(config: dict, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    js = (
        "// Auto-generated by generate_session_config.py — do not edit manually.\n"
        f"window.GENIUS_SESSION = {json.dumps(config, indent=2)};\n"
    )
    output.write_text(js)
    print(f"Written: {output}")
    for k in ("participantId", "sessionId", "condition", "desktopUrl", "username"):
        print(f"  {k:<16}: {config[k]}")
    print(f"  {'password':<16}: {'(set)' if config['password'] else '(not set)'}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--participant-id")
    parser.add_argument("--session-id", default=None)
    parser.add_argument("--condition", choices=["manual", "ai"])
    parser.add_argument("--desktop-url", default=None)
    parser.add_argument("--username", default=None)
    parser.add_argument("--password", default=None)
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT))
    args = parser.parse_args()

    env = {}
    if ENV_FILE.exists():
        env = parse_env_file(ENV_FILE)
    elif not (args.participant_id and args.condition):
        env = {k: os.environ.get(k, "") for k in
               ("PARTICIPANT_ID", "SESSION_ID", "CONDITION",
                "DESKTOP_URL", "DESKTOP_USERNAME", "DESKTOP_PASSWORD")}

    participant_id = args.participant_id or env.get("PARTICIPANT_ID", "").strip()
    session_id     = args.session_id     or env.get("SESSION_ID", "").strip() or "S1"
    condition      = args.condition      or env.get("CONDITION", "").strip().lower()
    desktop_url    = args.desktop_url    or env.get("DESKTOP_URL", "").strip()
    username       = args.username       or env.get("DESKTOP_USERNAME", "participant").strip() or "participant"
    password       = args.password       or env.get("DESKTOP_PASSWORD", "").strip()

    if not participant_id:
        print("ERROR: participant ID not found in session.env and not provided via --participant-id", file=sys.stderr)
        return 1

    if condition not in ("manual", "ai"):
        print(f"WARNING: condition '{condition}' is not 'manual' or 'ai' — defaulting to 'manual'", file=sys.stderr)
        condition = "manual"

    config = build_config(participant_id, session_id, condition, desktop_url, username, password)
    write_js(config, Path(args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
